name: deploy1

on:  
  workflow_dispatch:
  schedule:
  - cron: '0 11 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Step 1 - Python setup
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Step 2 - Test
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          checkName: test
          token: ${{ github.token }}
      - name: Step 3 - Getting dependencies
        run: pip install -r requirements.txt
      - name: Step 4 - Test run
        run: python ms_rewards_farmer.py --headless --accounts ${{ secrets.test1 }} 
